version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vuepress-theme-craftdocs
    versions:
    - 2.0.7
    - 2.0.8
  - dependency-name: vuepress
    versions:
    - 1.8.0
    - 1.8.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
